terraform {
  backend "azurerm" {
    resource_group_name = "NEWRG"
    storage_account_name = "mystorageacct12345762314"
    container_name       = "terraform"
    key                   = "terraform.tfstate"
  }
}
